name: CI

on: 
  push:
    branches:
    - 'master'
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - uses: warrenbuckley/Setup-MSBuild@v1

    - name: Restore
      shell: pwsh
      run: ./restore.ps1
    - name: Build
      run: msbuild ./Consul.sln /p:Configuration=Release /p:Platform=x86

    - name: Publish
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        artifact: '**\*.msi'
        body: Upstream release.
        token: ${{ secrets.GITHUB_TOKEN }}