name: CI

on: 
  push:
    branches:
    - 'master'
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore
      shell: pwsh
      run: ./restore.ps1
    - name: Build
      run: msbuild ./Consul.sln /p:Configuration=Release /p:Platform=x86

    - name: Publish (On Release Tags)
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        artifact: '**\*.msi'
        body: Upstream release.
        token: ${{ secrets.GITHUB_TOKEN }}