name: CI

# on: 
#   push:
#     tags:
#     - '*'

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - uses: warrenbuckley/Setup-MSBuild@v1

    - name: Restore
      shell: pwsh
      run: ./restore.ps1
    - name: Build
      run: msbuild ./Consul.sln /p:Configuration=Release /p:Platform=x86

    # - name: Create Release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "release.tar.gz,foo/*.txt"
    #     body: 
    #     token: ${{ secrets.GITHUB_TOKEN }}